default:
	g++ -o a.out main.cpp
	echo "000" | ./a.out
	echo "10010010" | ./a.out
	echo "0" | ./a.out
	echo "00" | ./a.out
	echo "001" | ./a.out
	echo "101" | ./a.out
	echo "11101" | ./a.out
	echo "1110100" | ./a.out
	echo "110" | ./a.out
	echo "1100" | ./a.out
	echo "110000" | ./a.out
	echo "1110000" | ./a.out
	echo "111111" | ./a.out
	echo "100101" | ./a.out
	echo "10010" | ./a.out
